<?php

$lang['num_word_0']        = 'Zero';
$lang['num_word_1']        = 'Un';
$lang['num_word_2']        = 'Dos';
$lang['num_word_3']        = 'Tres';
$lang['num_word_4']        = 'Quatre';
$lang['num_word_5']        = 'Cinc';
$lang['num_word_6']        = 'Sis';
$lang['num_word_7']        = 'Set';
$lang['num_word_8']        = 'Vuit';
$lang['num_word_9']        = 'Nou';
$lang['num_word_10']       = 'Deu';
$lang['num_word_11']       = 'Onze';
$lang['num_word_12']       = 'Dotze';
$lang['num_word_13']       = 'Tretze';
$lang['num_word_14']       = 'Catorze';
$lang['num_word_15']       = 'Quinze';
$lang['num_word_16']       = 'Setze';
$lang['num_word_17']       = 'Disset';
$lang['num_word_18']       = 'Divuit';
$lang['num_word_19']       = 'Dinou';
$lang['num_word_20']       = 'Vint';
$lang['num_word_21']       = 'Vint-i-un';
$lang['num_word_22']       = 'Vint-i-dos';
$lang['num_word_23']       = 'Vint-i-tres';
$lang['num_word_24']       = 'Vint-i-quatre';
$lang['num_word_25']       = 'Vint-i-cinc';
$lang['num_word_26']       = 'Vint-i-sis';
$lang['num_word_27']       = 'Vint-i-set';
$lang['num_word_28']       = 'Vint-i-vuit';
$lang['num_word_29']       = 'Vint-i-nou';
$lang['num_word_30']       = 'Trenta';
$lang['num_word_31']       = 'Trenta-un';
$lang['num_word_32']       = 'Trenta-dos';
$lang['num_word_33']       = 'Trenta-tres';
$lang['num_word_34']       = 'Trenta-quatre';
$lang['num_word_35']       = 'Trenta-cinc';
$lang['num_word_36']       = 'Trenta-sis';
$lang['num_word_37']       = 'Trenta-set';
$lang['num_word_38']       = 'Trenta-vuit';
$lang['num_word_39']       = 'Trenta-nou';
$lang['num_word_40']       = 'Quaranta';
$lang['num_word_41']       = 'Quaranta-un';
$lang['num_word_42']       = 'Quaranta-dos';
$lang['num_word_43']       = 'Quaranta-tres';
$lang['num_word_44']       = 'Quaranta-quatre';
$lang['num_word_45']       = 'Quaranta-cinc';
$lang['num_word_46']       = 'Quaranta-sis';
$lang['num_word_47']       = 'Quaranta-set';
$lang['num_word_48']       = 'Quaranta-vuit';
$lang['num_word_49']       = 'Quaranta-nou';
$lang['num_word_50']       = 'Cinquanta';
$lang['num_word_51']       = 'Cinquanta-un';
$lang['num_word_52']       = 'Cinquanta-dos';
$lang['num_word_53']       = 'Cinquanta-tres';
$lang['num_word_54']       = 'Cinquanta-quatre';
$lang['num_word_55']       = 'Cinquanta-cinc';
$lang['num_word_56']       = 'Cinquanta-sis';
$lang['num_word_57']       = 'Cinquanta-set';
$lang['num_word_58']       = 'Cinquanta-vuit';
$lang['num_word_59']       = 'Cinquanta-nou';
$lang['num_word_60']       = 'Seixanta';
$lang['num_word_61']       = 'Seixanta-un';
$lang['num_word_62']       = 'Seixanta-dos';
$lang['num_word_63']       = 'Seixanta-tres';
$lang['num_word_64']       = 'Seixanta-quatre';
$lang['num_word_65']       = 'Seixanta-cinc';
$lang['num_word_66']       = 'Seixanta-sis';
$lang['num_word_67']       = 'Seixanta-set';
$lang['num_word_68']       = 'Seixanta-vuit';
$lang['num_word_69']       = 'Seixanta-nou';
$lang['num_word_70']       = 'Setanta';
$lang['num_word_71']       = 'Setanta-un';
$lang['num_word_72']       = 'Setanta-dos';
$lang['num_word_73']       = 'Setanta-tres';
$lang['num_word_74']       = 'Setanta-quatre';
$lang['num_word_75']       = 'Setanta-cinc';
$lang['num_word_76']       = 'Setanta-sis';
$lang['num_word_77']       = 'Setanta-set';
$lang['num_word_78']       = 'Setanta-vuit';
$lang['num_word_79']       = 'Setanta-nou';
$lang['num_word_80']       = 'Vuitanta';
$lang['num_word_81']       = 'Vuitanta-un';
$lang['num_word_82']       = 'Vuitanta-dos';
$lang['num_word_83']       = 'Vuitanta-tres';
$lang['num_word_84']       = 'Vuitanta-quatre';
$lang['num_word_85']       = 'Vuitanta-cinc';
$lang['num_word_86']       = 'Vuitanta-sis';
$lang['num_word_87']       = 'Vuitanta-set';
$lang['num_word_88']       = 'Vuitanta-vuit';
$lang['num_word_89']       = 'Vuitanta-nou';
$lang['num_word_90']       = 'Noranta';
$lang['num_word_91']       = 'Noranta-un';
$lang['num_word_92']       = 'Noranta-dos';
$lang['num_word_93']       = 'Noranta-tres';
$lang['num_word_94']       = 'Noranta-quatre';
$lang['num_word_95']       = 'Noranta-cinc';
$lang['num_word_96']       = 'Noranta-sis';
$lang['num_word_97']       = 'Noranta-set';
$lang['num_word_98']       = 'Noranta-vuit';
$lang['num_word_99']       = 'Noranta-nou';
$lang['num_word_100']      = 'Cent';
$lang['num_word_200']      = 'Dos-cents';
$lang['num_word_300']      = 'Tres-cents';
$lang['num_word_400']      = 'Quatre-cents';
$lang['num_word_500']      = 'Cinc-cents';
$lang['num_word_600']      = 'Sis-cents';
$lang['num_word_700']      = 'Set-cents';
$lang['num_word_800']      = 'Vuit-cents';
$lang['num_word_900']      = 'Nou-cents';
$lang['num_word_thousand'] = 'Mil';
$lang['num_word_million']  = 'Milió';
$lang['num_word_billion']  = 'Bilió';
$lang['num_word_trillion'] = 'Trilió';
$lang['num_word_zillion']  = 'Zilió';
$lang['num_word_cents']    = 'Cèntims';
$lang['number_word_and']   = 'i';

# For Indian Customers, used with INR currency
$lang['num_word_hundred'] = 'Hundred';
$lang['num_word_lakh'] = 'Lakh';
$lang['num_word_lakhs'] = 'Lakh';

// Show in invoices and estimates
$lang['num_word'] = 'Amb paraules';

$currencies = [
    'USD' => 'Dòlars',
    'EUR' => 'Euros',
];

$currencies = hooks()->apply_filters('before_number_format_render_languge_currencies', $currencies);

foreach ($currencies as $key => $val) {
    $lang['num_word_' . strtoupper($key)] = $val;
}
