<?php

$lang['num_word_1']        = 'Unu';
$lang['num_word_2']        = 'Doi';
$lang['num_word_3']        = 'Trei';
$lang['num_word_4']        = 'Patru';
$lang['num_word_5']        = 'Cinci';
$lang['num_word_6']        = 'Sase';
$lang['num_word_7']        = 'Sapte';
$lang['num_word_8']        = 'Opt';
$lang['num_word_9']        = 'Noua';
$lang['num_word_10']       = 'Zece';
$lang['num_word_11']       = 'Unsprezece';
$lang['num_word_12']       = 'Doisprezece';
$lang['num_word_13']       = 'Treisprezece';
$lang['num_word_14']       = 'Paisprezece';
$lang['num_word_15']       = 'Cincisprezece';
$lang['num_word_16']       = 'Saisprezece';
$lang['num_word_17']       = 'Saptesprezece';
$lang['num_word_18']       = 'Optsprezece';
$lang['num_word_19']       = 'Nouasprezece';
$lang['num_word_20']       = 'Douazeci';
$lang['num_word_21']       = 'Douazeci si Unu';
$lang['num_word_22']       = 'Douazeci si Doi';
$lang['num_word_23']       = 'Douazeci si Trei';
$lang['num_word_24']       = 'Douazeci si Patru';
$lang['num_word_25']       = 'Douazeci si Cinci';
$lang['num_word_26']       = 'Douazeci si Sase';
$lang['num_word_27']       = 'Douazeci si Sapte';
$lang['num_word_28']       = 'Douazeci si Opt';
$lang['num_word_29']       = 'Douazeci si Noua';
$lang['num_word_30']       = 'Treizcei ';
$lang['num_word_31']       = 'Treizcei si Unu';
$lang['num_word_32']       = 'Treizcei si Doi';
$lang['num_word_33']       = 'Treizcei si Trei';
$lang['num_word_34']       = 'Treizcei si Patru';
$lang['num_word_35']       = 'Treizcei si Cinci';
$lang['num_word_36']       = 'Treizcei si Sase';
$lang['num_word_37']       = 'Treizcei si Sapte';
$lang['num_word_38']       = 'Treizcei si Opt';
$lang['num_word_39']       = 'Treizcei si Noua';
$lang['num_word_40']       = 'Patruzeci ';
$lang['num_word_41']       = 'Patruzeci si Unu';
$lang['num_word_42']       = 'Patruzeci si Doi';
$lang['num_word_43']       = 'Patruzeci si Trei';
$lang['num_word_44']       = 'Patruzeci si Patru';
$lang['num_word_45']       = 'Patruzeci si Cinci';
$lang['num_word_46']       = 'Patruzeci si Sase';
$lang['num_word_47']       = 'Patruzeci si Sapte';
$lang['num_word_48']       = 'Patruzeci si Opt';
$lang['num_word_49']       = 'Patruzeci si Noua';
$lang['num_word_50']       = 'Cincizeci ';
$lang['num_word_51']       = 'Cincizeci si Unu';
$lang['num_word_52']       = 'Cincizeci si Doi';
$lang['num_word_53']       = 'Cincizeci si Trei';
$lang['num_word_54']       = 'Cincizeci si Patru';
$lang['num_word_55']       = 'Cincizeci si Cinci';
$lang['num_word_56']       = 'Cincizeci si Sase';
$lang['num_word_57']       = 'Cincizeci si Sapte';
$lang['num_word_58']       = 'Cincizeci si Opt';
$lang['num_word_59']       = 'Cincizeci si Noua';
$lang['num_word_60']       = 'Saizeci ';
$lang['num_word_61']       = 'Saizeci si Unu';
$lang['num_word_62']       = 'Saizeci si Doi';
$lang['num_word_63']       = 'Saizeci si Trei';
$lang['num_word_64']       = 'Saizeci si Patru';
$lang['num_word_65']       = 'Saizeci si Cinci';
$lang['num_word_66']       = 'Saizeci si Sase';
$lang['num_word_67']       = 'Saizeci si Sapte';
$lang['num_word_68']       = 'Saizeci si Opt';
$lang['num_word_69']       = 'Saizeci si Noua';
$lang['num_word_70']       = 'Saptezeci ';
$lang['num_word_71']       = 'Saptezeci si Unu';
$lang['num_word_72']       = 'Saptezeci si Doi';
$lang['num_word_73']       = 'Saptezeci si Trei';
$lang['num_word_74']       = 'Saptezeci si Patru';
$lang['num_word_75']       = 'Saptezeci si Cinci';
$lang['num_word_76']       = 'Saptezeci si Sase';
$lang['num_word_77']       = 'Saptezeci si Sapte';
$lang['num_word_78']       = 'Saptezeci si Opt';
$lang['num_word_79']       = 'Saptezeci si Noua';
$lang['num_word_80']       = 'Optzeci';
$lang['num_word_81']       = 'Optzeci si Unu';
$lang['num_word_82']       = 'Optzeci si Doi';
$lang['num_word_83']       = 'Optzeci si Trei';
$lang['num_word_84']       = 'Optzeci si Patru';
$lang['num_word_85']       = 'Optzeci si Cinci';
$lang['num_word_86']       = 'Optzeci si Sase';
$lang['num_word_87']       = 'Optzeci si Sapte';
$lang['num_word_88']       = 'Optzeci si Opt';
$lang['num_word_89']       = 'Optzeci si Noua';
$lang['num_word_90']       = 'Nouazeci';
$lang['num_word_91']       = 'Nouazec si Unu';
$lang['num_word_92']       = 'Nouazec si Doi';
$lang['num_word_93']       = 'Nouazec si Trei';
$lang['num_word_94']       = 'Nouazec si Patru';
$lang['num_word_95']       = 'Nouazec si Cinci';
$lang['num_word_96']       = 'Nouazec si Sase';
$lang['num_word_97']       = 'Nouazec si Sapte';
$lang['num_word_98']       = 'Nouazec si Opt';
$lang['num_word_99']       = 'Nouazec si Noua';
$lang['num_word_100']      = 'O Suta';
$lang['num_word_200']      = 'Doi Sute';
$lang['num_word_300']      = 'Trei Sute';
$lang['num_word_400']      = 'Patru Sute';
$lang['num_word_500']      = 'Cinci Sute';
$lang['num_word_600']      = 'Sase Sute';
$lang['num_word_700']      = 'Sapte Sute';
$lang['num_word_800']      = 'Opt Sute';
$lang['num_word_900']      = 'Noua Sute';
$lang['num_word_thousand'] = 'Mie';
$lang['num_word_million']  = 'Milion';
$lang['num_word_billion']  = 'Miliard';
$lang['num_word_trillion'] = 'Trilion';
$lang['num_word_zillion']  = 'Catralioane';
$lang['num_word_cents']    = 'Centi';
$lang['number_word_and']   = 'Si';

# For Indian Customers, used with INR currency
$lang['num_word_hundred'] = 'Hundred';
$lang['num_word_lakh'] = 'Lakh';
$lang['num_word_lakhs'] = 'Lakh';

// Show in invoices and estimates
$lang['num_word'] = 'cu litere';

$currencies = [
    'USD' => 'Dolari',
    'EUR' => 'Euro',
    'RON' => 'Leu',
];

$currencies = hooks()->apply_filters('before_number_format_render_languge_currencies', $currencies);

foreach ($currencies as $key => $val) {
    $lang['num_word_' . strtoupper($key)] = $val;
}
