<?php

$lang['num_word_1']        = 'Um';
$lang['num_word_2']        = 'Dois';
$lang['num_word_3']        = 'Três';
$lang['num_word_4']        = 'Quatro';
$lang['num_word_5']        = 'Cinco';
$lang['num_word_6']        = 'Seis';
$lang['num_word_7']        = 'Sete';
$lang['num_word_8']        = 'Oito';
$lang['num_word_9']        = 'Nove';
$lang['num_word_10']       = 'Dez';
$lang['num_word_11']       = 'Onze';
$lang['num_word_12']       = 'Doze';
$lang['num_word_13']       = 'Treze';
$lang['num_word_14']       = 'Quatorze';
$lang['num_word_15']       = 'Quinze';
$lang['num_word_16']       = 'Dezesseis';
$lang['num_word_17']       = 'Dezessete';
$lang['num_word_18']       = 'Dezoito';
$lang['num_word_19']       = 'Dezenove';
$lang['num_word_20']       = 'Vinte';
$lang['num_word_21']       = 'Vinte e um';
$lang['num_word_22']       = 'Vinte e dois';
$lang['num_word_23']       = 'Vinte e três';
$lang['num_word_24']       = 'Vinte e quatro';
$lang['num_word_25']       = 'Vinte e cinco';
$lang['num_word_26']       = 'Vinte e seis';
$lang['num_word_27']       = 'Vinte e sete';
$lang['num_word_28']       = 'Vinte e oito';
$lang['num_word_29']       = 'Vinte e nove';
$lang['num_word_30']       = 'Trinta';
$lang['num_word_31']       = 'Trinta e um';
$lang['num_word_32']       = 'Trinta e dois';
$lang['num_word_33']       = 'Trinta e três';
$lang['num_word_34']       = 'Trinta e quatro';
$lang['num_word_35']       = 'Trinta e cinco';
$lang['num_word_36']       = 'Trinta e seis';
$lang['num_word_37']       = 'Trinta e sete';
$lang['num_word_38']       = 'Trinta e oito';
$lang['num_word_39']       = 'Trinta e nove';
$lang['num_word_40']       = 'Quarenta ';
$lang['num_word_41']       = 'Quarenta e um';
$lang['num_word_42']       = 'Quarenta e dois';
$lang['num_word_43']       = 'Quarenta e três';
$lang['num_word_44']       = 'Quarenta e quatro';
$lang['num_word_45']       = 'Quarenta e cinco';
$lang['num_word_46']       = 'Quarenta e seis';
$lang['num_word_47']       = 'Quarenta e sete';
$lang['num_word_48']       = 'Quarenta e oito';
$lang['num_word_49']       = 'Quarenta e nove';
$lang['num_word_50']       = 'Cinquenta e ';
$lang['num_word_51']       = 'Cinquenta e Um';
$lang['num_word_52']       = 'Cinquenta e Dois';
$lang['num_word_53']       = 'Cinquenta e Três';
$lang['num_word_54']       = 'Cinquenta e Quatro';
$lang['num_word_55']       = 'Cinquenta e Cinco';
$lang['num_word_56']       = 'Cinquenta e Seis';
$lang['num_word_57']       = 'Cinquenta e Sete';
$lang['num_word_58']       = 'Cinquenta e Oito';
$lang['num_word_59']       = 'Cinquenta e Nove';
$lang['num_word_60']       = 'Seisty';
$lang['num_word_61']       = 'Sessenta Um';
$lang['num_word_62']       = 'Sessenta e Dois';
$lang['num_word_63']       = 'Sessenta e Três';
$lang['num_word_64']       = 'Sessenta e Quatro';
$lang['num_word_65']       = 'Sessenta e Cinco';
$lang['num_word_66']       = 'Sessenta e Seis';
$lang['num_word_67']       = 'Sessenta e Sete';
$lang['num_word_68']       = 'Sessenta e Oito';
$lang['num_word_69']       = 'Sessenta e Nove';
$lang['num_word_70']       = 'Setenta';
$lang['num_word_71']       = 'Setenta e Um';
$lang['num_word_72']       = 'Setenta e Dois';
$lang['num_word_73']       = 'Setenta e Três';
$lang['num_word_74']       = 'Setenta e Quatro';
$lang['num_word_75']       = 'Setenta e Cinco';
$lang['num_word_76']       = 'Setenta e Seis';
$lang['num_word_77']       = 'Setenta e Sete';
$lang['num_word_78']       = 'Setenta e Oito';
$lang['num_word_79']       = 'Setenta e Nove';
$lang['num_word_80']       = 'Oitoy';
$lang['num_word_81']       = 'Oitenta Um';
$lang['num_word_82']       = 'Oitenta e Dois';
$lang['num_word_83']       = 'Oitenta e Três';
$lang['num_word_84']       = 'Oitenta e Quatro';
$lang['num_word_85']       = 'Oitenta e Cinco';
$lang['num_word_86']       = 'Oitenta e Seis';
$lang['num_word_87']       = 'Oitenta e Sete';
$lang['num_word_88']       = 'Oitenta e Oito';
$lang['num_word_89']       = 'Oitenta e Nove';
$lang['num_word_90']       = 'Noventa';
$lang['num_word_91']       = 'Noventa e Um';
$lang['num_word_92']       = 'Noventa e Dois';
$lang['num_word_93']       = 'Noventa e Três';
$lang['num_word_94']       = 'Noventa e Quatro';
$lang['num_word_95']       = 'Noventa e Cinco';
$lang['num_word_96']       = 'Noventa e Seis';
$lang['num_word_97']       = 'Noventa e Sete';
$lang['num_word_98']       = 'Noventa e Oito';
$lang['num_word_99']       = 'Noventa e Nove';
$lang['num_word_100']      = 'Cem';
$lang['num_word_200']      = 'Duzentos';
$lang['num_word_300']      = 'Trezentos';
$lang['num_word_400']      = 'Quatrocentos';
$lang['num_word_500']      = 'Quinhentos';
$lang['num_word_600']      = 'Seiscentos';
$lang['num_word_700']      = 'Setecentos';
$lang['num_word_800']      = 'Oitocentos';
$lang['num_word_900']      = 'Novecentos';
$lang['num_word_thousand'] = 'Mil';
$lang['num_word_million']  = 'Milhão';
$lang['num_word_billion']  = 'Bilhão';
$lang['num_word_trillion'] = 'Trilhão';
$lang['num_word_zillion']  = 'Zilhão';
$lang['num_word_cents']    = 'Centos';
$lang['number_word_and']   = 'e';

# For Indian Customers, used with INR currency
$lang['num_word_hundred'] = 'Hundred';
$lang['num_word_lakh'] = 'Lakh';
$lang['num_word_lakhs'] = 'Lakh';

// Show in invoices and estimates
$lang['num_word'] = 'Por extenso';

$currencies = [
    'USD' => 'Dólar',
    'EUR' => 'Euros',
];

$currencies = hooks()->apply_filters('before_number_format_render_languge_currencies', $currencies);

foreach ($currencies as $key => $val) {
    $lang['num_word_' . strtoupper($key)] = $val;
}
