<?php

$lang['num_word_0']        = 'Nula';
$lang['num_word_1']        = 'Jedna';
$lang['num_word_2']        = 'Dva';
$lang['num_word_3']        = 'Tøi';
$lang['num_word_4']        = 'Ètyøi';
$lang['num_word_5']        = 'Pìt';
$lang['num_word_6']        = 'Šest';
$lang['num_word_7']        = 'Sedm';
$lang['num_word_8']        = 'Osm';
$lang['num_word_9']        = 'Dìvìt';
$lang['num_word_10']       = 'Deset';
$lang['num_word_11']       = 'Jedenáct';
$lang['num_word_12']       = 'Dvanáct';
$lang['num_word_13']       = 'Tøináct';
$lang['num_word_14']       = 'Ètrnáct';
$lang['num_word_15']       = 'Patnáct';
$lang['num_word_16']       = 'Šestnáct';
$lang['num_word_17']       = 'Sedmnáct';
$lang['num_word_18']       = 'Osmnáct';
$lang['num_word_19']       = 'Devatenáct';
$lang['num_word_20']       = 'Dvacet';
$lang['num_word_21']       = 'Dvacet jedna';
$lang['num_word_22']       = 'Dvacet dva';
$lang['num_word_23']       = 'Dvacet tøi';
$lang['num_word_24']       = 'Dvacet ètyøi';
$lang['num_word_25']       = 'Dvacet pìt';
$lang['num_word_26']       = 'Dvacet šest';
$lang['num_word_27']       = 'Dvacet sedm';
$lang['num_word_28']       = 'Dvacet osm';
$lang['num_word_29']       = 'Dvacet devìt';
$lang['num_word_30']       = 'Tøicet';
$lang['num_word_31']       = 'Tøicet jedna';
$lang['num_word_32']       = 'Tøicet dva';
$lang['num_word_33']       = 'Tøicet tøi';
$lang['num_word_34']       = 'Tøicet ètyøi';
$lang['num_word_35']       = 'Tøicet pìt';
$lang['num_word_36']       = 'Tøicet šest';
$lang['num_word_37']       = 'Tøicet sedm';
$lang['num_word_38']       = 'Tøicet osm';
$lang['num_word_39']       = 'Tøicet devìt';
$lang['num_word_40']       = 'Ètyøicet';
$lang['num_word_41']       = 'Ètyøicet jedna';
$lang['num_word_42']       = 'Ètyøicet dva';
$lang['num_word_43']       = 'Ètyøicet tøi';
$lang['num_word_44']       = 'Ètyøicet ètyøi';
$lang['num_word_45']       = 'Ètyøicet pìt';
$lang['num_word_46']       = 'Ètyøicet šest';
$lang['num_word_47']       = 'Ètyøicet sedm';
$lang['num_word_48']       = 'Ètyøicet osm';
$lang['num_word_49']       = 'Ètyøicet devìt';
$lang['num_word_50']       = 'Padesát';
$lang['num_word_51']       = 'Padesát jedna';
$lang['num_word_52']       = 'Padesát dva';
$lang['num_word_53']       = 'Padesát tøi';
$lang['num_word_54']       = 'Padesát ètyøi';
$lang['num_word_55']       = 'Padesát pìt';
$lang['num_word_56']       = 'Padesát šest';
$lang['num_word_57']       = 'Padesát sedm';
$lang['num_word_58']       = 'Padesát osm';
$lang['num_word_59']       = 'Padesát devìt';
$lang['num_word_60']       = 'Šedesát';
$lang['num_word_61']       = 'Šedesát jedna';
$lang['num_word_62']       = 'Šedesát dva';
$lang['num_word_63']       = 'Šedesát tøi';
$lang['num_word_64']       = 'Šedesát ètyøi';
$lang['num_word_65']       = 'Šedesát pìt';
$lang['num_word_66']       = 'Šedesát šest';
$lang['num_word_67']       = 'Šedesát sedm';
$lang['num_word_68']       = 'Šedesát osm';
$lang['num_word_69']       = 'Šedesát devìt';
$lang['num_word_70']       = 'Sedmdesát';
$lang['num_word_71']       = 'Sedmdesát jedna';
$lang['num_word_72']       = 'Sedmdesát dva';
$lang['num_word_73']       = 'Sedmdesát tøi';
$lang['num_word_74']       = 'Sedmdesát ètyøi';
$lang['num_word_75']       = 'Sedmdesát pìt';
$lang['num_word_76']       = 'Sedmdesát šest';
$lang['num_word_77']       = 'Sedmdesát sedm';
$lang['num_word_78']       = 'Sedmdesát osm';
$lang['num_word_79']       = 'Sedmdesát devìt';
$lang['num_word_80']       = 'Osmdesát';
$lang['num_word_81']       = 'Osmdesát jedna';
$lang['num_word_82']       = 'Osmdesát dva';
$lang['num_word_83']       = 'Osmdesát tøi';
$lang['num_word_84']       = 'Osmdesát ètyøi';
$lang['num_word_85']       = 'Osmdesát pìt';
$lang['num_word_86']       = 'Osmdesát šest';
$lang['num_word_87']       = 'Osmdesát sedm';
$lang['num_word_88']       = 'Osmdesát osm';
$lang['num_word_89']       = 'Osmdesát devìt';
$lang['num_word_90']       = 'Devadesát';
$lang['num_word_91']       = 'Devadesát jedna';
$lang['num_word_92']       = 'Devadesát dva';
$lang['num_word_93']       = 'Devadesát tøi';
$lang['num_word_94']       = 'Devadesát ètyøi';
$lang['num_word_95']       = 'Devadesát pìt';
$lang['num_word_96']       = 'Devadesát šest';
$lang['num_word_97']       = 'Devadesát sedm';
$lang['num_word_98']       = 'Devadesát osm';
$lang['num_word_99']       = 'Devadesát devìt';
$lang['num_word_100']      = 'Sto';
$lang['num_word_200']      = 'Dvì stì';
$lang['num_word_300']      = 'Tøi sta';
$lang['num_word_400']      = 'Ètyøi sta';
$lang['num_word_500']      = 'Pìt set';
$lang['num_word_600']      = 'Šest set';
$lang['num_word_700']      = 'Sedm set';
$lang['num_word_800']      = 'Osm set';
$lang['num_word_900']      = 'Devìt set';
$lang['num_word_thousand'] = 'Tisíc';
$lang['num_word_million']  = 'Milión';
$lang['num_word_billion']  = 'Miliarda';
$lang['num_word_trillion'] = 'Bilion';
$lang['num_word_zillion']  = 'Zillion';
$lang['num_word_cents']    = 'haléøù';
$lang['number_word_and']   = 'a';

# For Indian Customers, used with INR currency
$lang['num_word_hundred'] = 'Sto';
$lang['num_word_lakh'] = 'Lakh';
$lang['num_word_lakhs'] = 'Lakh';

// Show in invoices and estimates
$lang['num_word'] = 'Slovy';

$currencies = [
    'USD' => 'Dolarù',
    'EUR' => 'Eur',
    'CZK' => 'Korun èeských',
];

$currencies = hooks()->apply_filters('before_number_format_render_languge_currencies', $currencies);

foreach ($currencies as $key => $val) {
    $lang['num_word_' . strtoupper($key)] = $val;
}
