<?php

$lang['num_word_0']        = 'Нуль';
$lang['num_word_1']        = 'Один';
$lang['num_word_2']        = 'Два';
$lang['num_word_3']        = 'Три';
$lang['num_word_4']        = 'Чотири';
$lang['num_word_5']        = 'П\'ять';
$lang['num_word_6']        = 'Шість';
$lang['num_word_7']        = 'Сім';
$lang['num_word_8']        = 'Вісім';
$lang['num_word_9']        = 'Дев\'ять';
$lang['num_word_10']       = 'Десять';
$lang['num_word_11']       = 'Одинадцять';
$lang['num_word_12']       = 'Дванадцять';
$lang['num_word_13']       = 'Тринадцять';
$lang['num_word_14']       = 'Чотирнадцять';
$lang['num_word_15']       = 'П\'ятнадцять';
$lang['num_word_16']       = 'Шістнадцять';
$lang['num_word_17']       = 'Сімнадцять';
$lang['num_word_18']       = 'Вісімнадцять';
$lang['num_word_19']       = 'Дев\'ятнадцять';
$lang['num_word_20']       = 'Двадцять';
$lang['num_word_21']       = 'Двадцять один';
$lang['num_word_22']       = 'Двадцять два';
$lang['num_word_23']       = 'Двадцять три';
$lang['num_word_24']       = 'Двадцять чотири';
$lang['num_word_25']       = 'Двадцять п\'ять';
$lang['num_word_26']       = 'Двадцять шість';
$lang['num_word_27']       = 'Двадцять сім';
$lang['num_word_28']       = 'Двадцять вісім';
$lang['num_word_29']       = 'Двадцять дев\'ять';
$lang['num_word_30']       = 'Тридцять';
$lang['num_word_31']       = 'Тридцять один';
$lang['num_word_32']       = 'Тридцять два';
$lang['num_word_33']       = 'Тридцять три';
$lang['num_word_34']       = 'Тридцять чотири';
$lang['num_word_35']       = 'Тридцять п\'ять';
$lang['num_word_36']       = 'Тридцять шість';
$lang['num_word_37']       = 'Тридцять сім';
$lang['num_word_38']       = 'Тридцять вісім';
$lang['num_word_39']       = 'Тридцять дев\'ять';
$lang['num_word_40']       = 'Сорок';
$lang['num_word_41']       = 'Сорок один';
$lang['num_word_42']       = 'Сорок два';
$lang['num_word_43']       = 'Сорок три';
$lang['num_word_44']       = 'Сорок чотири';
$lang['num_word_45']       = 'Сорок п\'ять';
$lang['num_word_46']       = 'Сорок шість';
$lang['num_word_47']       = 'Сорок сім';
$lang['num_word_48']       = 'Сорок вісім';
$lang['num_word_49']       = 'Сорок дев\'ять';
$lang['num_word_50']       = 'П\'ятдесят';
$lang['num_word_51']       = 'П\'ятдесят один';
$lang['num_word_52']       = 'П\'ятдесят два';
$lang['num_word_53']       = 'П\'ятдесят три';
$lang['num_word_54']       = 'П\'ятдесят чотири';
$lang['num_word_55']       = 'П\'ятдесят п\'ять';
$lang['num_word_56']       = 'П\'ятдесят шість';
$lang['num_word_57']       = 'П\'ятдесят сім';
$lang['num_word_58']       = 'П\'ятдесят вісім';
$lang['num_word_59']       = 'П\'ятдесят дев\'ять';
$lang['num_word_60']       = 'Шістдесят';
$lang['num_word_61']       = 'Шістдесят один';
$lang['num_word_62']       = 'Шістдесят два';
$lang['num_word_63']       = 'Шістдесят три';
$lang['num_word_64']       = 'Шістдесят чотири';
$lang['num_word_65']       = 'Шістдесят п\'ять';
$lang['num_word_66']       = 'Шістдесят шість';
$lang['num_word_67']       = 'Шістдесят сім';
$lang['num_word_68']       = 'Шістдесят вісім';
$lang['num_word_69']       = 'Шістдесят дев\'ять';
$lang['num_word_70']       = 'Сімдесят';
$lang['num_word_71']       = 'Сімдесят один';
$lang['num_word_72']       = 'Сімдесят два';
$lang['num_word_73']       = 'Сімдесят три';
$lang['num_word_74']       = 'Сімдесят чотири';
$lang['num_word_75']       = 'Сімдесят п\'ять';
$lang['num_word_76']       = 'Сімдесят шість';
$lang['num_word_77']       = 'Сімдесят сім';
$lang['num_word_78']       = 'Сімдесят вісім';
$lang['num_word_79']       = 'Сімдесят дев\'ять';
$lang['num_word_80']       = 'Вісімдесят';
$lang['num_word_81']       = 'Вісімдесят один';
$lang['num_word_82']       = 'Вісімдесят два';
$lang['num_word_83']       = 'Вісімдесят три';
$lang['num_word_84']       = 'Вісімдесят чотири';
$lang['num_word_85']       = 'Вісімдесят п\'ять';
$lang['num_word_86']       = 'Вісімдесят шість';
$lang['num_word_87']       = 'Вісімдесят сім';
$lang['num_word_88']       = 'Вісімдесят вісім';
$lang['num_word_89']       = 'Вісімдесят дев\'ять';
$lang['num_word_90']       = 'Дев\'яносто';
$lang['num_word_91']       = 'Дев\'яносто один';
$lang['num_word_92']       = 'Дев\'яносто два';
$lang['num_word_93']       = 'Дев\'яносто три';
$lang['num_word_94']       = 'Дев\'яносто чотири';
$lang['num_word_95']       = 'Дев\'яносто п\'ять';
$lang['num_word_96']       = 'Дев\'яносто шість';
$lang['num_word_97']       = 'Дев\'яносто сім';
$lang['num_word_98']       = 'Дев\'яносто вісім';
$lang['num_word_99']       = 'Дев\'яносто дев\'ять';
$lang['num_word_100']      = 'Сто';
$lang['num_word_200']      = 'Двісті';
$lang['num_word_300']      = 'Триста';
$lang['num_word_400']      = 'Чотириста';
$lang['num_word_500']      = 'П\'ятсот';
$lang['num_word_600']      = 'Шістсот';
$lang['num_word_700']      = 'Сімсот';
$lang['num_word_800']      = 'Вісімсот';
$lang['num_word_900']      = 'Дев\'ятсот';
$lang['num_word_thousand'] = 'Тисяча';
$lang['num_word_million']  = 'Мільйон';
$lang['num_word_billion']  = 'Мільярд';
$lang['num_word_trillion'] = 'Трильйон';
$lang['num_word_zillion']  = 'Зільйон';
$lang['num_word_cents']    = 'Копійок';
$lang['number_word_and']   = 'і';

# For Indian Customers, used with INR currency
$lang['num_word_hundred'] = 'Сто';
$lang['num_word_lakh']    = 'Сто тисяч';
$lang['num_word_lakhs']   = 'Сто тисяч';

// Show in invoices and estimates
$lang['num_word'] = 'Словами';

$currencies = [
    'USD' => 'Доларів',
    'EUR' => 'Євро',
    'UAH' => 'Гривень',
];

$currencies = hooks()->apply_filters('before_number_format_render_languge_currencies', $currencies);

foreach ($currencies as $key => $val) {
    $lang['num_word_' . strtoupper($key)] = $val;
}
