<?php

$lang['num_word_0']        = 'Zero';
$lang['num_word_1']        = 'Un';
$lang['num_word_2']        = 'Deux';
$lang['num_word_3']        = 'Trois';
$lang['num_word_4']        = 'Quatre';
$lang['num_word_5']        = 'Cinq';
$lang['num_word_6']        = 'Six';
$lang['num_word_7']        = 'Sept';
$lang['num_word_8']        = 'Huit';
$lang['num_word_9']        = 'Neuf';
$lang['num_word_10']       = 'Dix';
$lang['num_word_11']       = 'Onze';
$lang['num_word_12']       = 'Douze';
$lang['num_word_13']       = 'Treize';
$lang['num_word_14']       = 'Quatorze';
$lang['num_word_15']       = 'Quinze';
$lang['num_word_16']       = 'Seize';
$lang['num_word_17']       = 'Dix-sept';
$lang['num_word_18']       = 'Dix-huit';
$lang['num_word_19']       = 'Dix-neuf';
$lang['num_word_20']       = 'Vingt';
$lang['num_word_21']       = 'Vingt et un';
$lang['num_word_22']       = 'Vingt deux';
$lang['num_word_23']       = 'Vingt trois';
$lang['num_word_24']       = 'Vingt quatre';
$lang['num_word_25']       = 'Vingt cinq';
$lang['num_word_26']       = 'Vingt six';
$lang['num_word_27']       = 'Vingt sept';
$lang['num_word_28']       = 'Vingt huit';
$lang['num_word_29']       = 'Vingt neuf';
$lang['num_word_30']       = 'Trente';
$lang['num_word_31']       = 'Trente et un';
$lang['num_word_32']       = 'Trente deux';
$lang['num_word_33']       = 'Trente trois';
$lang['num_word_34']       = 'Trente quatre';
$lang['num_word_35']       = 'Trente cinq';
$lang['num_word_36']       = 'Trente six';
$lang['num_word_37']       = 'Trente sept';
$lang['num_word_38']       = 'Trente huit';
$lang['num_word_39']       = 'Trente neuf';
$lang['num_word_40']       = 'Quarante';
$lang['num_word_41']       = 'Quarante et un';
$lang['num_word_42']       = 'Quarante deux';
$lang['num_word_43']       = 'Quarante trois';
$lang['num_word_44']       = 'Quarante quatre';
$lang['num_word_45']       = 'Quarante cinq';
$lang['num_word_46']       = 'Quarante six';
$lang['num_word_47']       = 'Quarante sept';
$lang['num_word_48']       = 'Quarante huit';
$lang['num_word_49']       = 'Quarante neuf';
$lang['num_word_50']       = 'Cinquante';
$lang['num_word_51']       = 'Cinquante et un';
$lang['num_word_52']       = 'Cinquante deux';
$lang['num_word_53']       = 'Cinquante trois';
$lang['num_word_54']       = 'Cinquante quatre';
$lang['num_word_55']       = 'Cinquante cinq';
$lang['num_word_56']       = 'Cinquante six';
$lang['num_word_57']       = 'Cinquante sept';
$lang['num_word_58']       = 'Cinquante huit';
$lang['num_word_59']       = 'Cinquante neuf';
$lang['num_word_60']       = 'Soixante';
$lang['num_word_61']       = 'Soixante et un';
$lang['num_word_62']       = 'Soixante deux';
$lang['num_word_63']       = 'Soixante trois';
$lang['num_word_64']       = 'Soixante quatre';
$lang['num_word_65']       = 'Soixante cinq';
$lang['num_word_66']       = 'Soixante six';
$lang['num_word_67']       = 'Soixante sept';
$lang['num_word_68']       = 'Soixante huit';
$lang['num_word_69']       = 'Soixante neuf';
$lang['num_word_70']       = 'Soixante-dix';
$lang['num_word_71']       = 'Soixante-et-onze';
$lang['num_word_72']       = 'Soixante-douze';
$lang['num_word_73']       = 'Soixante-treize';
$lang['num_word_74']       = 'Soixante-quatorze';
$lang['num_word_75']       = 'Soixante-quinze';
$lang['num_word_76']       = 'Soixante-seize';
$lang['num_word_77']       = 'Soixante-dix-sept';
$lang['num_word_78']       = 'Soixante-dix-huit';
$lang['num_word_79']       = 'Soixante-dix-neuf';
$lang['num_word_80']       = 'Quatre-vingt';
$lang['num_word_81']       = 'Quatre-vingt-un';
$lang['num_word_82']       = 'Quatre-vingt deux';
$lang['num_word_83']       = 'Quatre-vingt trois';
$lang['num_word_84']       = 'Quatre-vingt quatre';
$lang['num_word_85']       = 'Quatre-vingt cinq';
$lang['num_word_86']       = 'Quatre-vingt six';
$lang['num_word_87']       = 'Quatre-vingt sept';
$lang['num_word_88']       = 'Quatre-vingt huit';
$lang['num_word_89']       = 'Quatre-vingt neuf';
$lang['num_word_90']       = 'Quatre-vingt-dix';
$lang['num_word_91']       = 'Quatre-vingt-onze';
$lang['num_word_92']       = 'Quatre-vingt-douze';
$lang['num_word_93']       = 'Quatre-vingt-treize';
$lang['num_word_94']       = 'Quatre-vingt-quatorze';
$lang['num_word_95']       = 'Quatre-vingt-quinze';
$lang['num_word_96']       = 'Quatre-vingt-seize';
$lang['num_word_97']       = 'Quatre-vingt-dix-sept';
$lang['num_word_98']       = 'Quatre-vingt-dix-huit';
$lang['num_word_99']       = 'Quatre-vingt-dix-neuf';
$lang['num_word_100']      = 'Cent';
$lang['num_word_200']      = 'Deux cent';
$lang['num_word_300']      = 'Trois cent';
$lang['num_word_400']      = 'Quatre cent';
$lang['num_word_500']      = 'Cinq cent';
$lang['num_word_600']      = 'Six cent';
$lang['num_word_700']      = 'Sept cent';
$lang['num_word_800']      = 'Huit cent';
$lang['num_word_900']      = 'Neuf cent';
$lang['num_word_thousand'] = 'Mille';
$lang['num_word_million']  = 'Million';
$lang['num_word_billion']  = 'Milliard';
$lang['num_word_trillion'] = 'Billion';
$lang['num_word_zillion']  = 'Zillion';
$lang['num_word_cents']    = 'Centimes';
$lang['number_word_and']   = 'et';

# For Indian Customers, used with INR currency
$lang['num_word_hundred'] = 'Hundred';
$lang['num_word_lakh'] = 'Lakh';
$lang['num_word_lakhs'] = 'Lakh';

// Show in invoices and estimates
$lang['num_word'] = 'En lettres';

$currencies       = [
    'USD' => 'Dollars',
    'EUR' => 'Euros',
];

$currencies = hooks()->apply_filters('before_number_format_render_languge_currencies', $currencies);

foreach ($currencies as $key => $val) {
    $lang['num_word_' . strtoupper($key)] = $val;
}
