<?php

$lang['num_word_1']        = 'Bir';
$lang['num_word_2']        = 'İki';
$lang['num_word_3']        = 'Üç';
$lang['num_word_4']        = 'Dört';
$lang['num_word_5']        = 'Beş';
$lang['num_word_6']        = 'Altı';
$lang['num_word_7']        = 'Yedi';
$lang['num_word_8']        = 'Sekiz';
$lang['num_word_9']        = 'Dokuz';
$lang['num_word_10']       = 'On';
$lang['num_word_11']       = 'On bir';
$lang['num_word_12']       = 'On iki';
$lang['num_word_13']       = 'On üç';
$lang['num_word_14']       = 'On dört';
$lang['num_word_15']       = 'On beş';
$lang['num_word_16']       = 'On altı';
$lang['num_word_17']       = 'On yedi';
$lang['num_word_18']       = 'On sekiz';
$lang['num_word_19']       = 'On dokuz';
$lang['num_word_20']       = 'Yirmi';
$lang['num_word_21']       = 'Yirmi bir';
$lang['num_word_22']       = 'Yirmi iki';
$lang['num_word_23']       = 'Yirmi üç';
$lang['num_word_24']       = 'Yirmi dört';
$lang['num_word_25']       = 'Yirmi beş';
$lang['num_word_26']       = 'Yirmi altı';
$lang['num_word_27']       = 'Yirmi yedi';
$lang['num_word_28']       = 'Yirmi sekiz';
$lang['num_word_29']       = 'Yirmi dokuz';
$lang['num_word_30']       = 'Otuz';
$lang['num_word_31']       = 'Otuz bir';
$lang['num_word_32']       = 'Otuz iki';
$lang['num_word_33']       = 'Otuz üç';
$lang['num_word_34']       = 'Otuz dört';
$lang['num_word_35']       = 'Otuz beş';
$lang['num_word_36']       = 'Otuz altı';
$lang['num_word_37']       = 'Otuz yedi';
$lang['num_word_38']       = 'Otuz sekiz';
$lang['num_word_39']       = 'Otuz dokuz';
$lang['num_word_40']       = 'Kırk';
$lang['num_word_41']       = 'Kırk bir';
$lang['num_word_42']       = 'Kırk iki';
$lang['num_word_43']       = 'Kırk üç';
$lang['num_word_44']       = 'Kırk dört';
$lang['num_word_45']       = 'Kırk beş';
$lang['num_word_46']       = 'Kırk altı';
$lang['num_word_47']       = 'Kırk yedi';
$lang['num_word_48']       = 'Kırk sekiz';
$lang['num_word_49']       = 'Kırk dokuz';
$lang['num_word_50']       = 'Elli';
$lang['num_word_51']       = 'Elli bir';
$lang['num_word_52']       = 'Elli iki';
$lang['num_word_53']       = 'Elli üç';
$lang['num_word_54']       = 'Elli dört';
$lang['num_word_55']       = 'Elli beş';
$lang['num_word_56']       = 'Elli altı';
$lang['num_word_57']       = 'Elli yedi';
$lang['num_word_58']       = 'Elli sekiz';
$lang['num_word_59']       = 'Elli dokuz';
$lang['num_word_60']       = 'Altmış';
$lang['num_word_61']       = 'Altmış bir';
$lang['num_word_62']       = 'Altmış iki';
$lang['num_word_63']       = 'Altmış üç';
$lang['num_word_64']       = 'Altmış dört';
$lang['num_word_65']       = 'Altmış beş';
$lang['num_word_66']       = 'Altmış altı';
$lang['num_word_67']       = 'Altmış yedi';
$lang['num_word_68']       = 'Altmış sekiz';
$lang['num_word_69']       = 'Altmış dokuz';
$lang['num_word_70']       = 'Yetmiş';
$lang['num_word_71']       = 'Yetmiş bir';
$lang['num_word_72']       = 'Yetmiş iki';
$lang['num_word_73']       = 'Yetmiş üç';
$lang['num_word_74']       = 'Yetmiş dört';
$lang['num_word_75']       = 'Yetmiş beş';
$lang['num_word_76']       = 'Yetmiş altı';
$lang['num_word_77']       = 'Yetmiş yedi';
$lang['num_word_78']       = 'Yetmiş sekiz';
$lang['num_word_79']       = 'Yetmiş dokuz';
$lang['num_word_80']       = 'Seksen';
$lang['num_word_81']       = 'Seksen bir';
$lang['num_word_82']       = 'Seksen iki';
$lang['num_word_83']       = 'Seksen üç';
$lang['num_word_84']       = 'Seksen dört';
$lang['num_word_85']       = 'Seksen beş';
$lang['num_word_86']       = 'Seksen altı';
$lang['num_word_87']       = 'Seksen yedi';
$lang['num_word_88']       = 'Seksen sekiz';
$lang['num_word_89']       = 'Seksen dokuz';
$lang['num_word_90']       = 'Doksan';
$lang['num_word_91']       = 'Doksan bir';
$lang['num_word_92']       = 'Doksan iki';
$lang['num_word_93']       = 'Doksan üç';
$lang['num_word_94']       = 'Doksan dört';
$lang['num_word_95']       = 'Doksan beş';
$lang['num_word_96']       = 'Doksan altı';
$lang['num_word_97']       = 'Doksan yedi';
$lang['num_word_98']       = 'Doksan sekiz';
$lang['num_word_99']       = 'Doksan dokuz';
$lang['num_word_100']      = 'Yüz';
$lang['num_word_200']      = 'İki yüz';
$lang['num_word_300']      = 'Üç yüz';
$lang['num_word_400']      = 'Dört yüz';
$lang['num_word_500']      = 'Beş yüz';
$lang['num_word_600']      = 'Altı yüz';
$lang['num_word_700']      = 'Yedi yüz';
$lang['num_word_800']      = 'Sekiz yüz';
$lang['num_word_900']      = 'Dokuz yüz';
$lang['num_word_thousand'] = 'Bin';
$lang['num_word_million']  = 'Milyon';
$lang['num_word_billion']  = 'Milyar';
$lang['num_word_trillion'] = 'Trilyon';
$lang['num_word_zillion']  = 'Zilyon';
$lang['num_word_cents']    = 'Kuruş';
$lang['number_word_and']   = 'Ve';

# For Indian Customers, used with INR currency
$lang['num_word_hundred'] = 'Hundred';
$lang['num_word_lakh'] = 'Lakh';
$lang['num_word_lakhs'] = 'Lakh';

// Show in invoices and estimates
$lang['num_word'] = 'Yazıyla';

$currencies = [
    'USD' => 'Dolar',
    'EUR' => 'Euro',
    'TRY' => 'Lira',
];

$currencies = hooks()->apply_filters('before_number_format_render_languge_currencies', $currencies);

foreach ($currencies as $key => $val) {
    $lang['num_word_' . strtoupper($key)] = $val;
}
