<?php

$lang['num_word_0']        = 'Zero';
$lang['num_word_1']        = 'Ett';
$lang['num_word_2']        = 'Två';
$lang['num_word_3']        = 'Tre';
$lang['num_word_4']        = 'Fyra';
$lang['num_word_5']        = 'Five';
$lang['num_word_6']        = 'Six';
$lang['num_word_7']        = 'Sju';
$lang['num_word_8']        = 'Åtta';
$lang['num_word_9']        = 'Nio';
$lang['num_word_10']       = 'Tio';
$lang['num_word_11']       = 'Elva';
$lang['num_word_12']       = 'Tolv';
$lang['num_word_13']       = 'Treton';
$lang['num_word_14']       = 'Fjorton';
$lang['num_word_15']       = 'Femton';
$lang['num_word_16']       = 'Sexton';
$lang['num_word_17']       = 'Sjuton';
$lang['num_word_18']       = 'Arton';
$lang['num_word_19']       = 'Nitton';
$lang['num_word_20']       = 'Tjugo';
$lang['num_word_21']       = 'Tjugoett';
$lang['num_word_22']       = 'TjugoTvå';
$lang['num_word_23']       = 'TjugoTre';
$lang['num_word_24']       = 'TjugoFyra';
$lang['num_word_25']       = 'TjugoFem';
$lang['num_word_26']       = 'TjugoSex';
$lang['num_word_27']       = 'TjugoSju';
$lang['num_word_28']       = 'TjugoÅtta';
$lang['num_word_29']       = 'TjugoNio';
$lang['num_word_30']       = 'Trettio';
$lang['num_word_31']       = 'Thirty One';
$lang['num_word_32']       = 'Thirty Two';
$lang['num_word_33']       = 'Thirty Three';
$lang['num_word_34']       = 'Thirty Four';
$lang['num_word_35']       = 'Thirty Five';
$lang['num_word_36']       = 'Thirty Six';
$lang['num_word_37']       = 'Thirty Seven';
$lang['num_word_38']       = 'Thirty Eight';
$lang['num_word_39']       = 'Thirty Nine';
$lang['num_word_40']       = 'Forty';
$lang['num_word_41']       = 'Forty One';
$lang['num_word_42']       = 'Forty Two';
$lang['num_word_43']       = 'Forty Three';
$lang['num_word_44']       = 'Forty Four';
$lang['num_word_45']       = 'Forty Five';
$lang['num_word_46']       = 'Forty Six';
$lang['num_word_47']       = 'Forty Seven';
$lang['num_word_48']       = 'Forty Eight';
$lang['num_word_49']       = 'Forty Nine';
$lang['num_word_50']       = 'Fifty';
$lang['num_word_51']       = 'Fifty One';
$lang['num_word_52']       = 'Fifty Two';
$lang['num_word_53']       = 'Fifty Three';
$lang['num_word_54']       = 'Fifty Four';
$lang['num_word_55']       = 'Fifty Five';
$lang['num_word_56']       = 'Fifty Six';
$lang['num_word_57']       = 'Fifty Seven';
$lang['num_word_58']       = 'Fifty Eight';
$lang['num_word_59']       = 'Fifty Nine';
$lang['num_word_60']       = 'Sixty';
$lang['num_word_61']       = 'Sixty One';
$lang['num_word_62']       = 'Sixty Two';
$lang['num_word_63']       = 'Sixty Three';
$lang['num_word_64']       = 'Sixty Four';
$lang['num_word_65']       = 'Sixty Five';
$lang['num_word_66']       = 'Sixty Six';
$lang['num_word_67']       = 'Sixty Seven';
$lang['num_word_68']       = 'Sixty Eight';
$lang['num_word_69']       = 'Sixty Nine';
$lang['num_word_70']       = 'Seventy';
$lang['num_word_71']       = 'Seventy One';
$lang['num_word_72']       = 'Seventy Two';
$lang['num_word_73']       = 'Seventy Three';
$lang['num_word_74']       = 'Seventy Four';
$lang['num_word_75']       = 'Seventy Five';
$lang['num_word_76']       = 'Seventy Six';
$lang['num_word_77']       = 'Seventy Seven';
$lang['num_word_78']       = 'Seventy Eight';
$lang['num_word_79']       = 'Seventy Nine';
$lang['num_word_80']       = 'Eighty';
$lang['num_word_81']       = 'Eighty One';
$lang['num_word_82']       = 'Eighty Two';
$lang['num_word_83']       = 'Eighty Three';
$lang['num_word_84']       = 'Eighty Four';
$lang['num_word_85']       = 'Eighty Five';
$lang['num_word_86']       = 'Eighty Six';
$lang['num_word_87']       = 'Eighty Seven';
$lang['num_word_88']       = 'Eighty Eight';
$lang['num_word_89']       = 'Eighty Nine';
$lang['num_word_90']       = 'Ninety';
$lang['num_word_91']       = 'Ninety One';
$lang['num_word_92']       = 'Ninety Two';
$lang['num_word_93']       = 'Ninety Three';
$lang['num_word_94']       = 'Ninety Four';
$lang['num_word_95']       = 'Ninety Five';
$lang['num_word_96']       = 'Ninety Six';
$lang['num_word_97']       = 'Ninety Seven';
$lang['num_word_98']       = 'Ninety Eight';
$lang['num_word_99']       = 'Ninety Nine';
$lang['num_word_100']      = 'EttHundra';
$lang['num_word_200']      = 'TvåHundra';
$lang['num_word_300']      = 'TreHundra';
$lang['num_word_400']      = 'FyraHundra';
$lang['num_word_500']      = 'FemHundra';
$lang['num_word_600']      = 'SexHundra';
$lang['num_word_700']      = 'SjuHundra';
$lang['num_word_800']      = 'ÅttaHundra';
$lang['num_word_900']      = 'NioHundra';
$lang['num_word_thousand'] = 'Tusen';
$lang['num_word_million']  = 'Million';
$lang['num_word_billion']  = 'Billion';
$lang['num_word_trillion'] = 'Trillion';
$lang['num_word_zillion']  = 'Zillion';
$lang['num_word_cents']    = 'Öre';
$lang['number_word_and']   = 'Och';

# For Indian Customers, used with INR currency
$lang['num_word_hundred'] = 'Hundred';
$lang['num_word_lakh'] = 'Lakh';
$lang['num_word_lakhs'] = 'Lakh';

// Show in invoices and estimates
$lang['num_word'] = 'Med andra ord';

$currencies = [
    'USD' => 'Dollars',
    'EUR' => 'Euros',
    'SEK' => 'Kronor',
];

$currencies = hooks()->apply_filters('before_number_format_render_languge_currencies', $currencies);

foreach ($currencies as $key => $val) {
    $lang['num_word_' . strtoupper($key)] = $val;
}
