<?php

$lang['num_word_1']        = 'Satu';
$lang['num_word_2']        = 'Dua';
$lang['num_word_3']        = 'Tiga';
$lang['num_word_4']        = 'Empat';
$lang['num_word_5']        = 'Lima';
$lang['num_word_6']        = 'Enam';
$lang['num_word_7']        = 'Tujuh';
$lang['num_word_8']        = 'Delapan';
$lang['num_word_9']        = 'Sembilan';
$lang['num_word_10']       = 'Sepuluh';
$lang['num_word_11']       = 'Sebelas';
$lang['num_word_12']       = 'Dua Belas';
$lang['num_word_13']       = 'Tiga Belas';
$lang['num_word_14']       = 'Empat Belas';
$lang['num_word_15']       = 'Lima Belas';
$lang['num_word_16']       = 'Enam Belas';
$lang['num_word_17']       = 'Tujuh Belas';
$lang['num_word_18']       = 'Delapan Belas';
$lang['num_word_19']       = 'Sembilan Belas';
$lang['num_word_20']       = 'Dua Puluh';
$lang['num_word_21']       = 'Dua Puluh Satu';
$lang['num_word_22']       = 'Dua Puluh Dua';
$lang['num_word_23']       = 'Dua Puluh Tiga';
$lang['num_word_24']       = 'Dua Puluh Empat';
$lang['num_word_25']       = 'Dua Puluh Lima';
$lang['num_word_26']       = 'Dua Puluh Enam';
$lang['num_word_27']       = 'Dua Puluh Tujuh';
$lang['num_word_28']       = 'Dua Puluh Delapan';
$lang['num_word_29']       = 'Dua Puluh Sembilan';
$lang['num_word_30']       = 'Tiga Puluh';
$lang['num_word_31']       = 'Tiga Puluh Satu';
$lang['num_word_32']       = 'Tiga Puluh Dua';
$lang['num_word_33']       = 'Tiga Puluh Tiga';
$lang['num_word_34']       = 'Tiga Puluh Empat';
$lang['num_word_35']       = 'Tiga Puluh Lima';
$lang['num_word_36']       = 'Tiga Puluh Enam';
$lang['num_word_37']       = 'Tiga Puluh Tujuh';
$lang['num_word_38']       = 'Tiga Puluh Delapan';
$lang['num_word_39']       = 'Tigapuluh Sembilan';
$lang['num_word_40']       = 'Empat Puluh';
$lang['num_word_41']       = 'Empat Puluh Satu';
$lang['num_word_42']       = 'Empat Puluh Dua';
$lang['num_word_43']       = 'Empat Puluh Tiga';
$lang['num_word_44']       = 'Empat Puluh Empat';
$lang['num_word_45']       = 'Empat Puluh Lima';
$lang['num_word_46']       = 'Empat Puluh Enam';
$lang['num_word_47']       = 'Empat Puluh Tujuh';
$lang['num_word_48']       = 'Empat Puluh Delapan';
$lang['num_word_49']       = 'Empat Puluh Sembilan';
$lang['num_word_50']       = 'Lima Puluh';
$lang['num_word_51']       = 'Lima Puluh Satu';
$lang['num_word_52']       = 'Lima Puluh Dua';
$lang['num_word_53']       = 'Lima Puluh Tiga';
$lang['num_word_54']       = 'Lima Puluh Empat';
$lang['num_word_55']       = 'Lima Puluh Lima';
$lang['num_word_56']       = 'Lima Puluh Enam';
$lang['num_word_57']       = 'Lima Puluh Tujuh';
$lang['num_word_58']       = 'Lima Puluh Delapan';
$lang['num_word_59']       = 'Lima Puluh Sembilan';
$lang['num_word_60']       = 'Enam Puluh';
$lang['num_word_61']       = 'Enam Puluh Satu';
$lang['num_word_62']       = 'Enam Puluh Dua';
$lang['num_word_63']       = 'Enam Puluh Tiga';
$lang['num_word_64']       = 'Enam Puluh Empat';
$lang['num_word_65']       = 'Enam Puluh Lima';
$lang['num_word_66']       = 'Enam Puluh Enam';
$lang['num_word_67']       = 'Enam Puluh Tujuh';
$lang['num_word_68']       = 'Enam Puluh Delapan';
$lang['num_word_69']       = 'Enam Puluh Sembilan';
$lang['num_word_70']       = 'Tujuh Puluh';
$lang['num_word_71']       = 'Tujuh Puluh Satu';
$lang['num_word_72']       = 'Tujuh Puluh Dua';
$lang['num_word_73']       = 'Tujuh Puluh Tiga';
$lang['num_word_74']       = 'Tujuh Puluh Empat';
$lang['num_word_75']       = 'Tujuh Puluh Lima';
$lang['num_word_76']       = 'Tujuh Puluh Enam';
$lang['num_word_77']       = 'Tujuh Puluh Tujuh';
$lang['num_word_78']       = 'Tujuh Puluh Delapan';
$lang['num_word_79']       = 'Tujuh Puluh Sembilan';
$lang['num_word_80']       = 'Delapan Puluh';
$lang['num_word_81']       = 'Delapan Puluh Satu';
$lang['num_word_82']       = 'Delapan Puluh Dua';
$lang['num_word_83']       = 'Delapan Puluh Tiga';
$lang['num_word_84']       = 'Delapan Puluh Empat';
$lang['num_word_85']       = 'Delapa Puluh Lima';
$lang['num_word_86']       = 'Delapan Puluh Enam';
$lang['num_word_87']       = 'Delapan Puluh Tujuh';
$lang['num_word_88']       = 'Delapan Puluh Delapan';
$lang['num_word_89']       = 'Delapan Puluh Sembilan';
$lang['num_word_90']       = 'Sembilan Puluh';
$lang['num_word_91']       = 'Sembilan Puluh Satu';
$lang['num_word_92']       = 'Sembilan Puluh Dua';
$lang['num_word_93']       = 'Sembilan Puluh Tiga';
$lang['num_word_94']       = 'Sembilan Puluh Empat';
$lang['num_word_95']       = 'Sembilan Puluh Lima';
$lang['num_word_96']       = 'Sembilan Puluh Enam';
$lang['num_word_97']       = 'Sembilan Puluh Tujuh';
$lang['num_word_98']       = 'Sembilan Puluh Delapan';
$lang['num_word_99']       = 'Sembilan Puluh Sembilan';
$lang['num_word_100']      = 'Seratus';
$lang['num_word_200']      = 'Dua ratus';
$lang['num_word_300']      = 'Tiga ratus';
$lang['num_word_400']      = 'Empat ratus';
$lang['num_word_500']      = 'Lima ratus';
$lang['num_word_600']      = 'Enam ratus';
$lang['num_word_700']      = 'Tujuh ratus';
$lang['num_word_800']      = 'Delapan ratus';
$lang['num_word_900']      = 'Sembilan ratus';
$lang['num_word_thousand'] = 'Ribu';
$lang['num_word_million']  = 'Juta';
$lang['num_word_billion']  = 'Milyar';
$lang['num_word_trillion'] = 'Triliun';
$lang['num_word_zillion']  = 'Kuadriliun';
$lang['num_word_cents']    = 'Sen';
$lang['number_word_and']   = '-';

# For Indian Customers, used with INR currency
$lang['num_word_hundred'] = 'Hundred';
$lang['num_word_lakh'] = 'Lakh';
$lang['num_word_lakhs'] = 'Lakh';

// Show in invoices and estimates
$lang['num_word'] = 'Terbilang';

$currencies = [
    'USD' => 'Dollars',
    'EUR' => 'Euros',
    'IDR' => 'Rupiah',
];

$currencies = hooks()->apply_filters('before_number_format_render_languge_currencies', $currencies);

foreach ($currencies as $key => $val) {
    $lang['num_word_' . strtoupper($key)] = $val;
}
