<?php

$lang['num_word_1']        = 'Jeden';
$lang['num_word_2']        = 'Dva';
$lang['num_word_3']        = 'Tri';
$lang['num_word_4']        = 'Štyri';
$lang['num_word_5']        = 'Päť';
$lang['num_word_6']        = 'Šesť';
$lang['num_word_7']        = 'Sedem';
$lang['num_word_8']        = 'Osem';
$lang['num_word_9']        = 'Deväť';
$lang['num_word_10']       = 'Desať';
$lang['num_word_11']       = 'Jedenásť';
$lang['num_word_12']       = 'Dvanásť';
$lang['num_word_13']       = 'Trinásť';
$lang['num_word_14']       = 'Štrnásť';
$lang['num_word_15']       = 'Pätnásť';
$lang['num_word_16']       = 'Šestnásť';
$lang['num_word_17']       = 'Sedemnásť';
$lang['num_word_18']       = 'Osemnásť';
$lang['num_word_19']       = 'Devätnásť';
$lang['num_word_20']       = 'Dvadsať';
$lang['num_word_21']       = 'Dvadsaťjeden';
$lang['num_word_22']       = 'Dvadsaťdva';
$lang['num_word_23']       = 'Dvadsaťtri';
$lang['num_word_24']       = 'Dvadsaťštyri';
$lang['num_word_25']       = 'Dvadsaťpäť';
$lang['num_word_26']       = 'Dvadsaťšesť';
$lang['num_word_27']       = 'Dvadsaťsedem';
$lang['num_word_28']       = 'Dvadsaťosem';
$lang['num_word_29']       = 'Dvadsaťdeväť';
$lang['num_word_30']       = 'Tridsať';
$lang['num_word_31']       = 'Tridsaťjeden';
$lang['num_word_32']       = 'Tridsaťdva';
$lang['num_word_33']       = 'Tridsaťtri';
$lang['num_word_34']       = 'Tridsaťštyri';
$lang['num_word_35']       = 'Tridsaťpäť';
$lang['num_word_36']       = 'Tridsaťšesť';
$lang['num_word_37']       = 'Tridsaťsedem';
$lang['num_word_38']       = 'Tridsaťosem';
$lang['num_word_39']       = 'Tridsaťdeväť';
$lang['num_word_40']       = 'Štyridsať';
$lang['num_word_41']       = 'Štyridsaťjeden';
$lang['num_word_42']       = 'Štyridsaťdva';
$lang['num_word_43']       = 'Štyridsaťtri';
$lang['num_word_44']       = 'Štyridsaťštyri';
$lang['num_word_45']       = 'Štyridsaťpäť';
$lang['num_word_46']       = 'Štyridsaťšesť';
$lang['num_word_47']       = 'Štyridsaťsedem';
$lang['num_word_48']       = 'Štyridsaťosem';
$lang['num_word_49']       = 'Štyridsaťdeväť';
$lang['num_word_50']       = 'Päťdesiat';
$lang['num_word_51']       = 'Päťdesiatjeden';
$lang['num_word_52']       = 'Päťdesiatdva';
$lang['num_word_53']       = 'Päťdesiattri';
$lang['num_word_54']       = 'Päťdesiatštyri';
$lang['num_word_55']       = 'Päťdesiatpäť';
$lang['num_word_56']       = 'Päťdesiatšesť';
$lang['num_word_57']       = 'Päťdesiatsedem';
$lang['num_word_58']       = 'Päťdesiatosem';
$lang['num_word_59']       = 'Päťdesiatdeväť';
$lang['num_word_60']       = 'Šesťdesiat';
$lang['num_word_61']       = 'Šesťdesiatjeden';
$lang['num_word_62']       = 'Šesťdesiatdva';
$lang['num_word_63']       = 'Šesťdesiattri';
$lang['num_word_64']       = 'Šesťdesiatštyri';
$lang['num_word_65']       = 'Šesťdesiatpäť';
$lang['num_word_66']       = 'Šesťdesiatšesť';
$lang['num_word_67']       = 'Šesťdesiatsedem';
$lang['num_word_68']       = 'Šesťdesiatosem';
$lang['num_word_69']       = 'Šesťdesiatdeväť';
$lang['num_word_70']       = 'Sedemdesiat';
$lang['num_word_71']       = 'Sedemdesiatjeden';
$lang['num_word_72']       = 'Sedemdesiatdva';
$lang['num_word_73']       = 'Sedemdesiattri';
$lang['num_word_74']       = 'Sedemdesiatštyri';
$lang['num_word_75']       = 'Sedemdesiatpäť';
$lang['num_word_76']       = 'Sedemdesiatšesť';
$lang['num_word_77']       = 'Sedemdesiatsedem';
$lang['num_word_78']       = 'Sedemdesiatosem';
$lang['num_word_79']       = 'Sedemdesiatdeväť';
$lang['num_word_80']       = 'Osemdesiat';
$lang['num_word_81']       = 'Osemdesiatjeden';
$lang['num_word_82']       = 'Osemdesiatdva';
$lang['num_word_83']       = 'Osemdesiattri';
$lang['num_word_84']       = 'Osemdesiatštyri';
$lang['num_word_85']       = 'Osemdesiatpäť';
$lang['num_word_86']       = 'Osemdesiatšesť';
$lang['num_word_87']       = 'Osemdesiatsedem';
$lang['num_word_88']       = 'Osemdesiatosem';
$lang['num_word_89']       = 'Osemdesiatdeväť';
$lang['num_word_90']       = 'Deväťdesiat';
$lang['num_word_91']       = 'Deväťdesiatjeden';
$lang['num_word_92']       = 'Deväťdesiatdva';
$lang['num_word_93']       = 'Deväťdesiattri';
$lang['num_word_94']       = 'Deväťdesiatštyri';
$lang['num_word_95']       = 'Deväťdesiatpäť';
$lang['num_word_96']       = 'Deväťdesiatšesť';
$lang['num_word_97']       = 'Deväťdesiatsedem';
$lang['num_word_98']       = 'Deväťdesiatosem';
$lang['num_word_99']       = 'Deväťdesiatdeväť';
$lang['num_word_100']      = 'Sto';
$lang['num_word_200']      = 'Dvesto';
$lang['num_word_300']      = 'Tristo';
$lang['num_word_400']      = 'Štyristo';
$lang['num_word_500']      = 'Päťsto';
$lang['num_word_600']      = 'Šesťsto';
$lang['num_word_700']      = 'Sedemsto';
$lang['num_word_800']      = 'Osemsto';
$lang['num_word_900']      = 'Deväťsto';
$lang['num_word_thousand'] = 'Tisíc';
$lang['num_word_million']  = 'Milión';
$lang['num_word_billion']  = 'Bilión';
$lang['num_word_trillion'] = 'Trilión';
$lang['num_word_zillion']  = 'Zilión';
$lang['num_word_cents']    = 'Centov';
$lang['number_word_and']   = 'a';

# For Indian Customers, used with INR currency
$lang['num_word_hundred'] = 'Hundred';
$lang['num_word_lakh'] = 'Lakh';
$lang['num_word_lakhs'] = 'Lakh';

// Show in invoices and estimates
$lang['num_word'] = 'slovom';

$currencies = [
    'USD' => 'Dolár',
    'EUR' => 'Euro',
];

$currencies = hooks()->apply_filters('before_number_format_render_languge_currencies', $currencies);

foreach ($currencies as $key => $val) {
    $lang['num_word_' . strtoupper($key)] = $val;
}
