<?php

$lang['num_word_0']        = 'Zero';
$lang['num_word_1']        = 'Uno';
$lang['num_word_2']        = 'Due';
$lang['num_word_3']        = 'Tre';
$lang['num_word_4']        = 'Quattro';
$lang['num_word_5']        = 'Cinque';
$lang['num_word_6']        = 'Sei';
$lang['num_word_7']        = 'Sette';
$lang['num_word_8']        = 'Otto';
$lang['num_word_9']        = 'Nove';
$lang['num_word_10']       = 'Dieci';
$lang['num_word_11']       = 'Undici';
$lang['num_word_12']       = 'Dodici';
$lang['num_word_13']       = 'Tredici';
$lang['num_word_14']       = 'Quattordici';
$lang['num_word_15']       = 'Quindici';
$lang['num_word_16']       = 'Sedici';
$lang['num_word_17']       = 'Diciassette';
$lang['num_word_18']       = 'Diciotto';
$lang['num_word_19']       = 'Diciannove';
$lang['num_word_20']       = 'Venti';
$lang['num_word_21']       = 'Ventuno';
$lang['num_word_22']       = 'Ventidue';
$lang['num_word_23']       = 'Ventitre';
$lang['num_word_24']       = 'Ventiquattro';
$lang['num_word_25']       = 'Venticinque';
$lang['num_word_26']       = 'Ventisei';
$lang['num_word_27']       = 'Ventisette';
$lang['num_word_28']       = 'Ventotto';
$lang['num_word_29']       = 'Ventinove';
$lang['num_word_30']       = 'Trenta';
$lang['num_word_31']       = 'Trentuno';
$lang['num_word_32']       = 'Trentadue';
$lang['num_word_33']       = 'Tretntatrè';
$lang['num_word_34']       = 'Trentaquattro';
$lang['num_word_35']       = 'Ttrentacinque';
$lang['num_word_36']       = 'Trentasei';
$lang['num_word_37']       = 'Trentasette';
$lang['num_word_38']       = 'Trentotto';
$lang['num_word_39']       = 'Trentanove';
$lang['num_word_40']       = 'Quaranta';
$lang['num_word_41']       = 'Quarantauno';
$lang['num_word_42']       = 'Quarantadue';
$lang['num_word_43']       = 'Quarantatre';
$lang['num_word_44']       = 'Quarantaquattro';
$lang['num_word_45']       = 'Quarantacinque';
$lang['num_word_46']       = 'Quarantasei';
$lang['num_word_47']       = 'Quarantasette';
$lang['num_word_48']       = 'Quarantotto';
$lang['num_word_49']       = 'Quarantanove';
$lang['num_word_50']       = 'Cinquanta';
$lang['num_word_51']       = 'Cinquanta uno';
$lang['num_word_52']       = 'Cinquantadue';
$lang['num_word_53']       = 'Cinquantatre';
$lang['num_word_54']       = 'Cinquantaquattro';
$lang['num_word_55']       = 'Cinquantacinque';
$lang['num_word_56']       = 'Cinquantasei';
$lang['num_word_57']       = 'Cinquantasette';
$lang['num_word_58']       = 'Cinquantotto';
$lang['num_word_59']       = 'Cinquantanove';
$lang['num_word_60']       = 'Sessanta';
$lang['num_word_61']       = 'Sessantauno';
$lang['num_word_62']       = 'Sessantadue';
$lang['num_word_63']       = 'Sessantatre';
$lang['num_word_64']       = 'Sessantaquattro';
$lang['num_word_65']       = 'Sessantacinque';
$lang['num_word_66']       = 'Sessantasei';
$lang['num_word_67']       = 'Sessantasette';
$lang['num_word_68']       = 'Sessantotto';
$lang['num_word_69']       = 'Sessantanove';
$lang['num_word_70']       = 'Settanta';
$lang['num_word_71']       = 'Settantauno';
$lang['num_word_72']       = 'Settantadue';
$lang['num_word_73']       = 'Settantatre';
$lang['num_word_74']       = 'Settantaquattro';
$lang['num_word_75']       = 'Settantacinque';
$lang['num_word_76']       = 'Settantasei';
$lang['num_word_77']       = 'Settantasette';
$lang['num_word_78']       = 'Settantantotto';
$lang['num_word_79']       = 'Settantanove';
$lang['num_word_80']       = 'Ottanta';
$lang['num_word_81']       = 'Ottantauno';
$lang['num_word_82']       = 'Ottantadue';
$lang['num_word_83']       = 'Ottantatre';
$lang['num_word_84']       = 'Ottantaquattro';
$lang['num_word_85']       = 'Ottantacinque';
$lang['num_word_86']       = 'Ottantasei';
$lang['num_word_87']       = 'Ottantasette';
$lang['num_word_88']       = 'Ottantantotto';
$lang['num_word_89']       = 'Ottantanove';
$lang['num_word_90']       = 'Novanta';
$lang['num_word_91']       = 'Novantauno';
$lang['num_word_92']       = 'Novantadue';
$lang['num_word_93']       = 'Novantatre';
$lang['num_word_94']       = 'Novantaquattro';
$lang['num_word_95']       = 'Novantacinque';
$lang['num_word_96']       = 'Novantasei';
$lang['num_word_97']       = 'Novantasette';
$lang['num_word_98']       = 'Novantotto';
$lang['num_word_99']       = 'Novantanove';
$lang['num_word_100']      = 'Cento';
$lang['num_word_200']      = 'Duecento';
$lang['num_word_300']      = 'Trecento';
$lang['num_word_400']      = 'Quattrocento';
$lang['num_word_500']      = 'Cinquecento';
$lang['num_word_600']      = 'Seicento';
$lang['num_word_700']      = 'Settecento';
$lang['num_word_800']      = 'Ottocento';
$lang['num_word_900']      = 'Novecento';
$lang['num_word_thousand'] = 'Mille';
$lang['num_word_million']  = 'Miliuno';
$lang['num_word_billion']  = 'Miliardo';
$lang['num_word_trillion'] = 'Trillioni';
$lang['num_word_zillion']  = 'Zillioni';
$lang['num_word_cents']    = 'Centesimi';
$lang['number_word_and']   = 'And';

# For Indian Customers, used with INR currency
$lang['num_word_hundred'] = 'Hundred';
$lang['num_word_lakh'] = 'Lakh';
$lang['num_word_lakhs'] = 'Lakh';

// Show in invoices and estimates
$lang['num_word'] = 'With words';

$currencies = [
    'USD' => 'Dollari',
    'EUR' => 'Euro',
];

$currencies = hooks()->apply_filters('before_number_format_render_languge_currencies', $currencies);

foreach ($currencies as $key => $val) {
    $lang['num_word_' . strtoupper($key)] = $val;
}
