<?php

$lang['num_word_0']        = 'Không';
$lang['num_word_1']        = 'Một';
$lang['num_word_2']        = 'Hai';
$lang['num_word_3']        = 'Ba';
$lang['num_word_4']        = 'Bốn';
$lang['num_word_5']        = 'Năm';
$lang['num_word_6']        = 'Sáu';
$lang['num_word_7']        = 'Bảy';
$lang['num_word_8']        = 'Tám';
$lang['num_word_9']        = 'Chín';
$lang['num_word_10']       = 'Mười';
$lang['num_word_11']       = 'Mười một';
$lang['num_word_12']       = 'Mười hai';
$lang['num_word_13']       = 'Mười ba';
$lang['num_word_14']       = 'Mười bốn';
$lang['num_word_15']       = 'Mười lăm';
$lang['num_word_16']       = 'Mười sáu';
$lang['num_word_17']       = 'Mười bảy';
$lang['num_word_18']       = 'Mười tám';
$lang['num_word_19']       = 'Mười chín';
$lang['num_word_20']       = 'Hai mươi';
$lang['num_word_21']       = 'Hai mươi mốt';
$lang['num_word_22']       = 'Hai mươi hai';
$lang['num_word_23']       = 'Hai mươi ba';
$lang['num_word_24']       = 'Hai mươi bốn';
$lang['num_word_25']       = 'Hai mươi lăm';
$lang['num_word_26']       = 'Hai mươi sáu';
$lang['num_word_27']       = 'Hai mươi bảy';
$lang['num_word_28']       = 'Hai mươi tám';
$lang['num_word_29']       = 'Hai mươi chín';
$lang['num_word_30']       = 'Ba mươi';
$lang['num_word_31']       = 'Ba mươi mốt';
$lang['num_word_32']       = 'Ba mươi hai';
$lang['num_word_33']       = 'Ba mươi ba';
$lang['num_word_34']       = 'Ba mươi bốn';
$lang['num_word_35']       = 'Ba mươi lăm';
$lang['num_word_36']       = 'Ba mươi sáu';
$lang['num_word_37']       = 'Ba mươi bảy';
$lang['num_word_38']       = 'Ba mươi tám';
$lang['num_word_39']       = 'Ba mươi chín';
$lang['num_word_40']       = 'Bốn mươi';
$lang['num_word_41']       = 'Bốn mươi mốt';
$lang['num_word_42']       = 'Bốn mươi hai';
$lang['num_word_43']       = 'Bốn mươi ba';
$lang['num_word_44']       = 'Bốn mươi bốn';
$lang['num_word_45']       = 'Bốn mươi lăm';
$lang['num_word_46']       = 'Bốn mươi sáu';
$lang['num_word_47']       = 'Bốn mươi bảy';
$lang['num_word_48']       = 'Bốn mươi tám';
$lang['num_word_49']       = 'Bốn mươi chín';
$lang['num_word_50']       = 'Năm mươi';
$lang['num_word_51']       = 'Năm mươi mốt';
$lang['num_word_52']       = 'Năm mươi hai';
$lang['num_word_53']       = 'Năm mươi ba';
$lang['num_word_54']       = 'Năm mươi bốn';
$lang['num_word_55']       = 'Năm mươi lăm';
$lang['num_word_56']       = 'Năm mươi sáu';
$lang['num_word_57']       = 'Năm mươi bảy';
$lang['num_word_58']       = 'Năm mươi tám';
$lang['num_word_59']       = 'Năm mươi chín';
$lang['num_word_60']       = 'Sáu mươi';
$lang['num_word_61']       = 'Sáu mươi mốt';
$lang['num_word_62']       = 'Sáu mươi hai';
$lang['num_word_63']       = 'Sáu mươi ba';
$lang['num_word_64']       = 'Sáu mươi bốn';
$lang['num_word_65']       = 'Sáu mươi lăm';
$lang['num_word_66']       = 'Sáu mươi sáu';
$lang['num_word_67']       = 'Sáu mươi bảy';
$lang['num_word_68']       = 'Sáu mươi tám';
$lang['num_word_69']       = 'Sáu mươi chín';
$lang['num_word_70']       = 'Bảy mươi';
$lang['num_word_71']       = 'Bảy mươi mốt';
$lang['num_word_72']       = 'Bảy mươi hai';
$lang['num_word_73']       = 'Bảy mươi ba';
$lang['num_word_74']       = 'Bảy mươi bốn';
$lang['num_word_75']       = 'Bảy mươi lăm';
$lang['num_word_76']       = 'Bảy mươi sáu';
$lang['num_word_77']       = 'Bảy mươi bảy';
$lang['num_word_78']       = 'Bảy mươi tám';
$lang['num_word_79']       = 'Bảy mươi chín';
$lang['num_word_80']       = 'Tám mươi';
$lang['num_word_81']       = 'Tám mươi mốt';
$lang['num_word_82']       = 'Tám mươi hai';
$lang['num_word_83']       = 'Tám mươi ba';
$lang['num_word_84']       = 'Tám mươi bốn';
$lang['num_word_85']       = 'Tám mươi lăm';
$lang['num_word_86']       = 'Tám mươi sáu';
$lang['num_word_87']       = 'Tám mươi bảy';
$lang['num_word_88']       = 'Tám mươi tám';
$lang['num_word_89']       = 'Tám mươi chín';
$lang['num_word_90']       = 'Chín mươi';
$lang['num_word_91']       = 'Chín mươi mốt';
$lang['num_word_92']       = 'Chín mươi hai';
$lang['num_word_93']       = 'Chín mươi ba';
$lang['num_word_94']       = 'Chín mươi bốn';
$lang['num_word_95']       = 'Chín mươi lăm';
$lang['num_word_96']       = 'Chín mươi sáu';
$lang['num_word_97']       = 'Chín mươi bảy';
$lang['num_word_98']       = 'Chín mươi tám';
$lang['num_word_99']       = 'Chín mươi chín';
$lang['num_word_100']      = 'Một trăm';
$lang['num_word_200']      = 'Hai trăm';
$lang['num_word_300']      = 'Ba trăm';
$lang['num_word_400']      = 'Bốn trăm';
$lang['num_word_500']      = 'Năm trăm';
$lang['num_word_600']      = 'Sáu trăm';
$lang['num_word_700']      = 'Bảy trăm';
$lang['num_word_800']      = 'Tám trăm';
$lang['num_word_900']      = 'Chín trăm';
$lang['num_word_thousand'] = 'Nghìn';
$lang['num_word_million']  = 'Triệu';
$lang['num_word_billion']  = 'Tỷ';
$lang['num_word_trillion'] = 'Nghìn tỷ';
$lang['num_word_zillion']  = 'Trăm nghìn tỷ';
$lang['num_word_cents']    = 'Xu';
$lang['number_word_and']   = 'và';

# For Indian Customers, used with INR currency
$lang['num_word_hundred'] = 'Hundred';
$lang['num_word_lakh'] = 'Lakh';
$lang['num_word_lakhs'] = 'Lakh';

// Show in invoices and estimates
$lang['num_word'] = 'Bằng chữ';

$currencies = [
    'USD' => 'Đô-la',
    'EUR' => 'Ơ-rô',
    'VND' => 'Đồng',
];

$currencies = hooks()->apply_filters('before_number_format_render_languge_currencies', $currencies);

foreach ($currencies as $key => $val) {
    $lang['num_word_' . strtoupper($key)] = $val;
}
