<?php

$lang['num_word_1']        = 'Один';
$lang['num_word_2']        = 'Два';
$lang['num_word_3']        = 'Три';
$lang['num_word_4']        = 'Четыре';
$lang['num_word_5']        = 'Пять';
$lang['num_word_6']        = 'Шесть';
$lang['num_word_7']        = 'Семь';
$lang['num_word_8']        = 'Восемь';
$lang['num_word_9']        = 'Девять';
$lang['num_word_10']       = 'Десять';
$lang['num_word_11']       = 'Одиннадцать';
$lang['num_word_12']       = 'Двенадцать';
$lang['num_word_13']       = 'Тринадцать';
$lang['num_word_14']       = 'Четырнадцать';
$lang['num_word_15']       = 'Пятнадцать';
$lang['num_word_16']       = 'Шестнадцать';
$lang['num_word_17']       = 'Семнадцать';
$lang['num_word_18']       = 'Восемнадцать';
$lang['num_word_19']       = 'Девятнадцать';
$lang['num_word_20']       = 'Двадцать';
$lang['num_word_21']       = 'Двадцать один';
$lang['num_word_22']       = 'Двадцать два';
$lang['num_word_23']       = 'Двадцать три';
$lang['num_word_24']       = 'Двадцать четыре';
$lang['num_word_25']       = 'Двадцать пять';
$lang['num_word_26']       = 'Двадцать шесть';
$lang['num_word_27']       = 'Двадцать семь';
$lang['num_word_28']       = 'Двадцать восемь';
$lang['num_word_29']       = 'Двадцать девять';
$lang['num_word_30']       = 'Тридцать';
$lang['num_word_31']       = 'Тридцать один';
$lang['num_word_32']       = 'Тридцать два';
$lang['num_word_33']       = 'Тридцать три';
$lang['num_word_34']       = 'Тридцать четыре';
$lang['num_word_35']       = 'Тридцать пять';
$lang['num_word_36']       = 'Тридцать шесть';
$lang['num_word_37']       = 'Тридцать семь';
$lang['num_word_38']       = 'Тридцать восемь';
$lang['num_word_39']       = 'Тридцать девять';
$lang['num_word_40']       = 'Сорок';
$lang['num_word_41']       = 'Сорок один';
$lang['num_word_42']       = 'Сорок два';
$lang['num_word_43']       = 'Сорок три';
$lang['num_word_44']       = 'Сорок четыре';
$lang['num_word_45']       = 'Сорок пять';
$lang['num_word_46']       = 'Сорок шесть';
$lang['num_word_47']       = 'Сорок семь';
$lang['num_word_48']       = 'Сорок восемь';
$lang['num_word_49']       = 'Сорок девять';
$lang['num_word_50']       = 'Пятьдесят';
$lang['num_word_51']       = 'Пятьдесят один';
$lang['num_word_52']       = 'Пятьдесят два';
$lang['num_word_53']       = 'Пятьдесят три';
$lang['num_word_54']       = 'Пятьдесят четыре';
$lang['num_word_55']       = 'Пятьдесят пять';
$lang['num_word_56']       = 'Пятьдесят шесть';
$lang['num_word_57']       = 'Пятьдесят семь';
$lang['num_word_58']       = 'Пятьдесят восемь';
$lang['num_word_59']       = 'Пятьдесят девять';
$lang['num_word_60']       = 'Шестьдесят';
$lang['num_word_61']       = 'Шестьдесят один';
$lang['num_word_62']       = 'Шестьдесят два';
$lang['num_word_63']       = 'Шестьдесят три';
$lang['num_word_64']       = 'Шестьдесят четыре';
$lang['num_word_65']       = 'Шестьдесят пять';
$lang['num_word_66']       = 'Шестьдесят шесть';
$lang['num_word_67']       = 'Шестьдесят семь';
$lang['num_word_68']       = 'Шестьдесят восемь';
$lang['num_word_69']       = 'Шестьдесят девять';
$lang['num_word_70']       = 'Семьдесят';
$lang['num_word_71']       = 'Семьдесят один';
$lang['num_word_72']       = 'Семьдесят два';
$lang['num_word_73']       = 'Семьдесят три';
$lang['num_word_74']       = 'Семьдесят четыре';
$lang['num_word_75']       = 'Семьдесят пять';
$lang['num_word_76']       = 'Семьдесят шесть';
$lang['num_word_77']       = 'Семьдесят семь';
$lang['num_word_78']       = 'Семьдесят восемь';
$lang['num_word_79']       = 'Семьдесят девять';
$lang['num_word_80']       = 'Восемьдесят';
$lang['num_word_81']       = 'Восемьдесят один';
$lang['num_word_82']       = 'Восемьдесят два';
$lang['num_word_83']       = 'Восемьдесят три';
$lang['num_word_84']       = 'Восемьдесят четыре';
$lang['num_word_85']       = 'Восемьдесят пять';
$lang['num_word_86']       = 'Восемьдесят шесть';
$lang['num_word_87']       = 'Восемьдесят семь';
$lang['num_word_88']       = 'Восемьдесят восемь';
$lang['num_word_89']       = 'Восемьдесят девять';
$lang['num_word_90']       = 'Девяносто';
$lang['num_word_91']       = 'Девяносто один';
$lang['num_word_92']       = 'Девяносто два';
$lang['num_word_93']       = 'Девяносто три';
$lang['num_word_94']       = 'Девяносто четыре';
$lang['num_word_95']       = 'Девяносто пять';
$lang['num_word_96']       = 'Девяносто шесть';
$lang['num_word_97']       = 'Девяносто семь';
$lang['num_word_98']       = 'Девяносто восемь';
$lang['num_word_99']       = 'Девяносто девять';
$lang['num_word_100']      = 'Сто';
$lang['num_word_200']      = 'Двести';
$lang['num_word_300']      = 'Триста';
$lang['num_word_400']      = 'Четыреста';
$lang['num_word_500']      = 'Пятьсот';
$lang['num_word_600']      = 'Шестьсот';
$lang['num_word_700']      = 'Семьсот';
$lang['num_word_800']      = 'Восемьсот';
$lang['num_word_900']      = 'Девятьсот';
$lang['num_word_thousand'] = 'Тысяча';
$lang['num_word_million']  = 'Миллион';
$lang['num_word_billion']  = 'Миллиард';
$lang['num_word_trillion'] = 'Триллион';
$lang['num_word_zillion']  = 'Зиллион';
$lang['num_word_cents']    = 'Копеек';
$lang['number_word_and']   = 'и';

# For Indian Customers, used with INR currency
$lang['num_word_hundred'] = 'Сто';
$lang['num_word_lakh'] = 'Сто тысяч';
$lang['num_word_lakhs'] = 'Сто тысяч';

// Show in invoices and estimates
$lang['num_word'] = 'Словами';

$currencies = [
    'USD' => 'Долларов',
    'EUR' => 'Евро',
    'RUB' => 'Рублей',
];

$currencies = hooks()->apply_filters('before_number_format_render_languge_currencies', $currencies);

foreach ($currencies as $key => $val) {
    $lang['num_word_' . strtoupper($key)] = $val;
}
