<?php

$lang['num_word_1']        = 'Yksi';
$lang['num_word_2']        = 'Kaksi';
$lang['num_word_3']        = 'Kolme';
$lang['num_word_4']        = 'Neljä';
$lang['num_word_5']        = 'Viisi';
$lang['num_word_6']        = 'Kuusi';
$lang['num_word_7']        = 'Seitsemän';
$lang['num_word_8']        = 'Kahdeksan';
$lang['num_word_9']        = 'Yhdeksän';
$lang['num_word_10']       = 'Kymmenen';
$lang['num_word_11']       = 'Yksitoista';
$lang['num_word_12']       = 'Kaksitoista';
$lang['num_word_13']       = 'Kolmetoista';
$lang['num_word_14']       = 'Neljätoista';
$lang['num_word_15']       = 'Viisitoista';
$lang['num_word_16']       = 'Kuusitoista';
$lang['num_word_17']       = 'Seitsemäntoista';
$lang['num_word_18']       = 'Kahdeksantoista';
$lang['num_word_19']       = 'Yhdeksäntoista';
$lang['num_word_20']       = 'Kaksikymmentä';
$lang['num_word_21']       = 'Kaksikymmentäyksi';
$lang['num_word_22']       = 'Kaksikymmentäkaksi';
$lang['num_word_23']       = 'Kaksikymmentäkolme';
$lang['num_word_24']       = 'Kaksikymmentäneljä';
$lang['num_word_25']       = 'Kaksikymmentäviisi';
$lang['num_word_26']       = 'Kaksikymmentäkuusi';
$lang['num_word_27']       = 'Kaksikymmentäseitsemän';
$lang['num_word_28']       = 'Kaksikymmentäkahdeksan';
$lang['num_word_29']       = 'Kaksikymmentäyhdeksän';
$lang['num_word_30']       = 'Kolmekymmentä';
$lang['num_word_31']       = 'Kolmekymmentäyksi';
$lang['num_word_32']       = 'Kolmekymmentäkaksi';
$lang['num_word_33']       = 'Kolmekymmentäkolme';
$lang['num_word_34']       = 'Kolmekymmentäneljä';
$lang['num_word_35']       = 'Kolmekymmentäviisi';
$lang['num_word_36']       = 'Kolmekymmentäkuusi';
$lang['num_word_37']       = 'Kolmekymmentäseitsemän';
$lang['num_word_38']       = 'Kolmekymmentäkahdeksan';
$lang['num_word_39']       = 'Kolmekymmentäyhdeksän';
$lang['num_word_40']       = 'Neljäkymmentä';
$lang['num_word_41']       = 'Neljäkymmentäyksi';
$lang['num_word_42']       = 'Neljäkymmentäkaksi';
$lang['num_word_43']       = 'Neljäkymmentäkolme';
$lang['num_word_44']       = 'Neljäkymmentäneljä';
$lang['num_word_45']       = 'Neljäkymmentäviisi';
$lang['num_word_46']       = 'Neljäkymmentäkuusi';
$lang['num_word_47']       = 'Neljäkymmentäseitsemän';
$lang['num_word_48']       = 'Neljäkymmentäkahdeksan';
$lang['num_word_49']       = 'Neljäkymmentäyhdeksän';
$lang['num_word_50']       = 'Viisikymmentä';
$lang['num_word_51']       = 'Viisikymmentäyksi';
$lang['num_word_52']       = 'Viisikymmentäkaksi';
$lang['num_word_53']       = 'Viisikymmentäkolme';
$lang['num_word_54']       = 'Viisikymmentäneljä';
$lang['num_word_55']       = 'Viisikymmentäviisi';
$lang['num_word_56']       = 'Viisikymmentäkuusi';
$lang['num_word_57']       = 'Viisikymmentäseitsemän';
$lang['num_word_58']       = 'Viisikymmentäkahdeksan';
$lang['num_word_59']       = 'Viisikymmentäyhdeksän';
$lang['num_word_60']       = 'Kuusikymmentä';
$lang['num_word_61']       = 'Kuusikymmentäyksi';
$lang['num_word_62']       = 'Kuusikymmentäkaksi';
$lang['num_word_63']       = 'Kuusikymmentäkolme';
$lang['num_word_64']       = 'Kuusikymmentäneljä';
$lang['num_word_65']       = 'Kuusikymmentäviisi';
$lang['num_word_66']       = 'Kuusikymmentäkuusi';
$lang['num_word_67']       = 'Kuusikymmentäseitsemän';
$lang['num_word_68']       = 'Kuusikymmentäkahdeksan';
$lang['num_word_69']       = 'Kuusikymmentäyhdeksän';
$lang['num_word_70']       = 'Seitsemänkymmentä';
$lang['num_word_71']       = 'Seitsemänkymmentäyksi';
$lang['num_word_72']       = 'Seitsemänkymmentäkaksi';
$lang['num_word_73']       = 'Seitsemänkymmentäkolme';
$lang['num_word_74']       = 'Seitsemänkymmentäneljä';
$lang['num_word_75']       = 'Seitsemänkymmentäviisi';
$lang['num_word_76']       = 'Seitsemänkymmentäkuusi';
$lang['num_word_77']       = 'Seitsemänkymmentäseitsemän';
$lang['num_word_78']       = 'Seitsemänkymmentäkahdeksan';
$lang['num_word_79']       = 'Seitsemänkymmentäyhdeksän';
$lang['num_word_80']       = 'Kahdeksankymmentä';
$lang['num_word_81']       = 'Kahdeksankymmentäyksi';
$lang['num_word_82']       = 'Kahdeksankymmentäkaksi';
$lang['num_word_83']       = 'Kahdeksankymmentäkolme';
$lang['num_word_84']       = 'Kahdeksankymmentäneljä';
$lang['num_word_85']       = 'Kahdeksankymmentäviisi';
$lang['num_word_86']       = 'Kahdeksankymmentäkuusi';
$lang['num_word_87']       = 'Kahdeksankymmentäseitsemän';
$lang['num_word_88']       = 'Kahdeksankymmentäkahdeksan';
$lang['num_word_89']       = 'Kahdeksankymmentäyhdeksän';
$lang['num_word_90']       = 'Yhdeksänkymmentä';
$lang['num_word_91']       = 'Yhdeksänkymmentäyksi';
$lang['num_word_92']       = 'Yhdeksänkymmentäkaksi';
$lang['num_word_93']       = 'Yhdeksänkymmentäkolme';
$lang['num_word_94']       = 'Yhdeksänkymmentäneljä';
$lang['num_word_95']       = 'Yhdeksänkymmentäviisi';
$lang['num_word_96']       = 'Yhdeksänkymmentäkuusi';
$lang['num_word_97']       = 'Yhdeksänkymmentäseitsemän';
$lang['num_word_98']       = 'Yhdeksänkymmentäkahdeksan';
$lang['num_word_99']       = 'Yhdeksänkymmentäyhdeksän';
$lang['num_word_100']      = 'Sata';
$lang['num_word_200']      = 'Kaksisataa';
$lang['num_word_300']      = 'Kolmesataa';
$lang['num_word_400']      = 'Neljäsataa';
$lang['num_word_500']      = 'Viisisataa';
$lang['num_word_600']      = 'Kuusisataa';
$lang['num_word_700']      = 'Seitsemänsataa';
$lang['num_word_800']      = 'Kahdeksansataa';
$lang['num_word_900']      = 'Yhdeksänsataa';
$lang['num_word_thousand'] = 'Tuhat';
$lang['num_word_million']  = 'Miljoona';
$lang['num_word_billion']  = 'Miljardi';
$lang['num_word_trillion'] = 'biljoona';
$lang['num_word_zillion']  = 'Zillion';
$lang['num_word_cents']    = 'senttiä';
$lang['number_word_and']   = 'Ja';

# For Indian Customers, used with INR currency
$lang['num_word_hundred'] = 'Hundred';
$lang['num_word_lakh'] = 'Lakh';
$lang['num_word_lakhs'] = 'Lakh';

// Show in invoices and estimates
$lang['num_word'] = 'Sanoin';

$currencies = [
    'USD' => 'Dollaria',
    'EUR' => 'Euroa',
];

$currencies = hooks()->apply_filters('before_number_format_render_languge_currencies', $currencies);

foreach ($currencies as $key => $val) {
    $lang['num_word_' . strtoupper($key)] = $val;
}
